USE [master]
GO
/****** Object:  Database [MathOperation]    Script Date: 10-08-2023 17:37:54 ******/
CREATE DATABASE [MathOperation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MathOperation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MathOperation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MathOperation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MathOperation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MathOperation] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MathOperation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MathOperation] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MathOperation] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MathOperation] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MathOperation] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MathOperation] SET ARITHABORT OFF 
GO
ALTER DATABASE [MathOperation] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MathOperation] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MathOperation] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MathOperation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MathOperation] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MathOperation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MathOperation] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MathOperation] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MathOperation] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MathOperation] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MathOperation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MathOperation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MathOperation] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MathOperation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MathOperation] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MathOperation] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [MathOperation] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MathOperation] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MathOperation] SET  MULTI_USER 
GO
ALTER DATABASE [MathOperation] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MathOperation] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MathOperation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MathOperation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MathOperation] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MathOperation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MathOperation] SET QUERY_STORE = OFF
GO
USE [MathOperation]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10-08-2023 17:37:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tblSum]    Script Date: 10-08-2023 17:37:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tblSum](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Num1] [int] NOT NULL,
	[Num2] [int] NOT NULL,
	[Total] [int] NOT NULL,
 CONSTRAINT [PK_tblSum] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tblSum] ADD  DEFAULT ((0)) FOR [Total]
GO
USE [master]
GO
ALTER DATABASE [MathOperation] SET  READ_WRITE 
GO
